
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";

-- --------------------------------------------------------
INSERT INTO `lc_countries` (`id`, `status`, `name`, `domestic_name`, `iso_code_2`, `iso_code_3`, `address_format`, `postcode_required`, `currency_code`, `phone_code`, `date_updated`, `date_created`) VALUES
(1, 0, 'Afghanistan', '', 'AF', 'AFG', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(2, 0, 'Albania', '', 'AL', 'ALB', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(3, 0, 'Algeria', '', 'DZ', 'DZA', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(4, 0, 'American Samoa', '', 'AS', 'ASM', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(5, 0, 'Andorra', '', 'AD', 'AND', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(6, 0, 'Angola', '', 'AO', 'AGO', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(7, 0, 'Anguilla', '', 'AI', 'AIA', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(8, 0, 'Antarctica', '', 'AQ', 'ATA', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(9, 0, 'Antigua and Barbuda', '', 'AG', 'ATG', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(10, 0, 'Argentina', '', 'AR', 'ARG', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(11, 0, 'Armenia', '', 'AM', 'ARM', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(12, 0, 'Aruba', '', 'AW', 'ABW', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(13, 1, 'Australia', '', 'AU', 'AUS', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(14, 0, 'Austria', '', 'AT', 'AUT', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(15, 0, 'Azerbaijan', '', 'AZ', 'AZE', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(16, 0, 'Bahamas', '', 'BS', 'BHS', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(17, 0, 'Bahrain', '', 'BH', 'BHR', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(18, 0, 'Bangladesh', '', 'BD', 'BGD', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(19, 0, 'Barbados', '', 'BB', 'BRB', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(20, 0, 'Belarus', '', 'BY', 'BLR', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(21, 1, 'Belgium', '', 'BE', 'BEL', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(22, 0, 'Belize', '', 'BZ', 'BLZ', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(23, 0, 'Benin', '', 'BJ', 'BEN', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(24, 0, 'Bermuda', '', 'BM', 'BMU', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(25, 0, 'Bhutan', '', 'BT', 'BTN', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(26, 0, 'Bolivia', '', 'BO', 'BOL', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(27, 0, 'Bosnia and Herzegowina', '', 'BA', 'BIH', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(28, 0, 'Botswana', '', 'BW', 'BWA', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(29, 0, 'Bouvet Island', '', 'BV', 'BVT', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(30, 0, 'Brazil', '', 'BR', 'BRA', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(31, 0, 'British Indian Ocean Territory', '', 'IO', 'IOT', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(32, 0, 'Brunei Darussalam', '', 'BN', 'BRN', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(33, 0, 'Bulgaria', '', 'BG', 'BGR', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(34, 0, 'Burkina Faso', '', 'BF', 'BFA', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(35, 0, 'Burundi', '', 'BI', 'BDI', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(36, 0, 'Cambodia', '', 'KH', 'KHM', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(37, 0, 'Cameroon', '', 'CM', 'CMR', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(38, 0, 'Canada', '', 'CA', 'CAN', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(39, 0, 'Cape Verde', '', 'CV', 'CPV', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(40, 0, 'Cayman Islands', '', 'KY', 'CYM', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(41, 0, 'Central African Republic', '', 'CF', 'CAF', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(42, 0, 'Chad', '', 'TD', 'TCD', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(43, 0, 'Chile', '', 'CL', 'CHL', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(44, 0, 'China', '', 'CN', 'CHN', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(45, 0, 'Christmas Island', '', 'CX', 'CXR', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(46, 0, 'Cocos (Keeling) Islands', '', 'CC', 'CCK', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(47, 0, 'Colombia', '', 'CO', 'COL', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(48, 0, 'Comoros', '', 'KM', 'COM', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(49, 0, 'Congo', '', 'CG', 'COG', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(50, 0, 'Cook Islands', '', 'CK', 'COK', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(51, 0, 'Costa Rica', '', 'CR', 'CRI', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(52, 0, 'Cote D''Ivoire', '', 'CI', 'CIV', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(53, 0, 'Croatia', '', 'HR', 'HRV', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(54, 0, 'Cuba', '', 'CU', 'CUB', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(55, 0, 'Cyprus', '', 'CY', 'CYP', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(56, 0, 'Czech Republic', '', 'CZ', 'CZE', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(57, 1, 'Denmark', '', 'DK', 'DNK', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(58, 0, 'Djibouti', '', 'DJ', 'DJI', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(59, 0, 'Dominica', '', 'DM', 'DMA', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(60, 0, 'Dominican Republic', '', 'DO', 'DOM', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(61, 0, 'East Timor', '', 'TP', 'TMP', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(62, 0, 'Ecuador', '', 'EC', 'ECU', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(63, 0, 'Egypt', '', 'EG', 'EGY', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(64, 0, 'El Salvador', '', 'SV', 'SLV', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(65, 0, 'Equatorial Guinea', '', 'GQ', 'GNQ', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(66, 0, 'Eritrea', '', 'ER', 'ERI', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(67, 0, 'Estonia', '', 'EE', 'EST', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(68, 0, 'Ethiopia', '', 'ET', 'ETH', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(69, 0, 'Falkland Islands (Malvinas)', '', 'FK', 'FLK', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(70, 0, 'Faroe Islands', '', 'FO', 'FRO', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(71, 0, 'Fiji', '', 'FJ', 'FJI', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(72, 1, 'Finland', '', 'FI', 'FIN', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(73, 1, 'France', '', 'FR', 'FRA', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(74, 0, 'France, Metropolitan', '', 'FX', 'FXX', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(75, 0, 'French Guiana', '', 'GF', 'GUF', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(76, 0, 'French Polynesia', '', 'PF', 'PYF', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(77, 0, 'French Southern Territories', '', 'TF', 'ATF', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(78, 0, 'Gabon', '', 'GA', 'GAB', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(79, 0, 'Gambia', '', 'GM', 'GMB', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(80, 0, 'Georgia', '', 'GE', 'GEO', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(81, 1, 'Germany', '', 'DE', 'DEU', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(82, 0, 'Ghana', '', 'GH', 'GHA', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(83, 0, 'Gibraltar', '', 'GI', 'GIB', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(84, 0, 'Greece', '', 'GR', 'GRC', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(85, 0, 'Greenland', '', 'GL', 'GRL', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(86, 0, 'Grenada', '', 'GD', 'GRD', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(87, 0, 'Guadeloupe', '', 'GP', 'GLP', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(88, 0, 'Guam', '', 'GU', 'GUM', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(89, 0, 'Guatemala', '', 'GT', 'GTM', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(90, 0, 'Guinea', '', 'GN', 'GIN', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(91, 0, 'Guinea-bissau', '', 'GW', 'GNB', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(92, 0, 'Guyana', '', 'GY', 'GUY', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(93, 0, 'Haiti', '', 'HT', 'HTI', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(94, 0, 'Heard and Mc Donald Islands', '', 'HM', 'HMD', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(95, 0, 'Honduras', '', 'HN', 'HND', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(96, 0, 'Hong Kong', '', 'HK', 'HKG', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(97, 0, 'Hungary', '', 'HU', 'HUN', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(98, 0, 'Iceland', '', 'IS', 'ISL', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(99, 0, 'India', '', 'IN', 'IND', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(100, 0, 'Indonesia', '', 'ID', 'IDN', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(101, 0, 'Iran (Islamic Republic of)', '', 'IR', 'IRN', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(102, 0, 'Iraq', '', 'IQ', 'IRQ', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(103, 0, 'Ireland', '', 'IE', 'IRL', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(104, 0, 'Israel', '', 'IL', 'ISR', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(105, 0, 'Italy', '', 'IT', 'ITA', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(106, 0, 'Jamaica', '', 'JM', 'JAM', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(107, 0, 'Japan', '', 'JP', 'JPN', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(108, 0, 'Jordan', '', 'JO', 'JOR', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(109, 0, 'Kazakhstan', '', 'KZ', 'KAZ', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(110, 0, 'Kenya', '', 'KE', 'KEN', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(111, 0, 'Kiribati', '', 'KI', 'KIR', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(112, 0, 'North Korea', '', 'KP', 'PRK', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(113, 0, 'Korea, Republic of', '', 'KR', 'KOR', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(114, 0, 'Kuwait', '', 'KW', 'KWT', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(115, 0, 'Kyrgyzstan', '', 'KG', 'KGZ', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(116, 0, 'Lao People''s Democratic Republic', '', 'LA', 'LAO', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(117, 0, 'Latvia', '', 'LV', 'LVA', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(118, 0, 'Lebanon', '', 'LB', 'LBN', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(119, 0, 'Lesotho', '', 'LS', 'LSO', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(120, 0, 'Liberia', '', 'LR', 'LBR', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(121, 0, 'Libyan Arab Jamahiriya', '', 'LY', 'LBY', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(122, 0, 'Liechtenstein', '', 'LI', 'LIE', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(123, 0, 'Lithuania', '', 'LT', 'LTU', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(124, 0, 'Luxembourg', '', 'LU', 'LUX', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(125, 0, 'Macau', '', 'MO', 'MAC', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(126, 0, 'Macedonia', '', 'MK', 'MKD', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(127, 0, 'Madagascar', '', 'MG', 'MDG', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(128, 0, 'Malawi', '', 'MW', 'MWI', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(129, 0, 'Malaysia', '', 'MY', 'MYS', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(130, 0, 'Maldives', '', 'MV', 'MDV', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(131, 0, 'Mali', '', 'ML', 'MLI', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(132, 0, 'Malta', '', 'MT', 'MLT', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(133, 0, 'Marshall Islands', '', 'MH', 'MHL', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(134, 0, 'Martinique', '', 'MQ', 'MTQ', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(135, 0, 'Mauritania', '', 'MR', 'MRT', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(136, 0, 'Mauritius', '', 'MU', 'MUS', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(137, 0, 'Mayotte', '', 'YT', 'MYT', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(138, 0, 'Mexico', '', 'MX', 'MEX', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(139, 0, 'Micronesia, Federated States of', '', 'FM', 'FSM', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(140, 0, 'Moldova, Republic of', '', 'MD', 'MDA', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(141, 0, 'Monaco', '', 'MC', 'MCO', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(142, 0, 'Mongolia', '', 'MN', 'MNG', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(143, 0, 'Montserrat', '', 'MS', 'MSR', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(144, 0, 'Morocco', '', 'MA', 'MAR', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(145, 0, 'Mozambique', '', 'MZ', 'MOZ', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(146, 0, 'Myanmar', '', 'MM', 'MMR', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(147, 0, 'Namibia', '', 'NA', 'NAM', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(148, 0, 'Nauru', '', 'NR', 'NRU', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(149, 0, 'Nepal', '', 'NP', 'NPL', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(150, 1, 'Netherlands', '', 'NL', 'NLD', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(151, 0, 'Netherlands Antilles', '', 'AN', 'ANT', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(152, 0, 'New Caledonia', '', 'NC', 'NCL', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(153, 0, 'New Zealand', '', 'NZ', 'NZL', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(154, 0, 'Nicaragua', '', 'NI', 'NIC', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(155, 0, 'Niger', '', 'NE', 'NER', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(156, 0, 'Nigeria', '', 'NG', 'NGA', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(157, 0, 'Niue', '', 'NU', 'NIU', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(158, 0, 'Norfolk Island', '', 'NF', 'NFK', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(159, 0, 'Northern Mariana Islands', '', 'MP', 'MNP', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(160, 1, 'Norway', '', 'NO', 'NOR', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(161, 0, 'Oman', '', 'OM', 'OMN', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(162, 0, 'Pakistan', '', 'PK', 'PAK', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(163, 0, 'Palau', '', 'PW', 'PLW', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(164, 0, 'Panama', '', 'PA', 'PAN', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(165, 0, 'Papua New Guinea', '', 'PG', 'PNG', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(166, 0, 'Paraguay', '', 'PY', 'PRY', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(167, 0, 'Peru', '', 'PE', 'PER', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(168, 0, 'Philippines', '', 'PH', 'PHL', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(169, 0, 'Pitcairn', '', 'PN', 'PCN', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(170, 0, 'Poland', '', 'PL', 'POL', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(171, 1, 'Portugal', '', 'PT', 'PRT', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(172, 0, 'Puerto Rico', '', 'PR', 'PRI', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(173, 0, 'Qatar', '', 'QA', 'QAT', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(174, 0, 'Reunion', '', 'RE', 'REU', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(175, 0, 'Romania', '', 'RO', 'ROM', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(176, 0, 'Russian Federation', '', 'RU', 'RUS', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(177, 0, 'Rwanda', '', 'RW', 'RWA', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(178, 0, 'Saint Kitts and Nevis', '', 'KN', 'KNA', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(179, 0, 'Saint Lucia', '', 'LC', 'LCA', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(180, 0, 'Saint Vincent and the Grenadines', '', 'VC', 'VCT', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(181, 0, 'Samoa', '', 'WS', 'WSM', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(182, 0, 'San Marino', '', 'SM', 'SMR', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(183, 0, 'Sao Tome and Principe', '', 'ST', 'STP', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(184, 0, 'Saudi Arabia', '', 'SA', 'SAU', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(185, 0, 'Senegal', '', 'SN', 'SEN', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(186, 0, 'Seychelles', '', 'SC', 'SYC', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(187, 0, 'Sierra Leone', '', 'SL', 'SLE', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(188, 0, 'Singapore', '', 'SG', 'SGP', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(189, 0, 'Slovak Republic', '', 'SK', 'SVK', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(190, 0, 'Slovenia', '', 'SI', 'SVN', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(191, 0, 'Solomon Islands', '', 'SB', 'SLB', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(192, 0, 'Somalia', '', 'SO', 'SOM', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(193, 0, 'South Africa', '', 'ZA', 'ZAF', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(194, 0, 'South Georgia &amp; South Sandwich Islands', '', 'GS', 'SGS', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(195, 1, 'Spain', '', 'ES', 'ESP', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(196, 0, 'Sri Lanka', '', 'LK', 'LKA', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(197, 0, 'St. Helena', '', 'SH', 'SHN', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(198, 0, 'St. Pierre and Miquelon', '', 'PM', 'SPM', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(199, 0, 'Sudan', '', 'SD', 'SDN', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(200, 0, 'Suriname', '', 'SR', 'SUR', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(201, 0, 'Svalbard and Jan Mayen Islands', '', 'SJ', 'SJM', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(202, 0, 'Swaziland', '', 'SZ', 'SWZ', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(203, 1, 'Sweden', '', 'SE', 'SWE', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(204, 0, 'Switzerland', '', 'CH', 'CHE', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(205, 0, 'Syrian Arab Republic', '', 'SY', 'SYR', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(206, 0, 'Taiwan', '', 'TW', 'TWN', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(207, 0, 'Tajikistan', '', 'TJ', 'TJK', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(208, 0, 'Tanzania, United Republic of', '', 'TZ', 'TZA', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(209, 0, 'Thailand', '', 'TH', 'THA', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(210, 0, 'Togo', '', 'TG', 'TGO', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(211, 0, 'Tokelau', '', 'TK', 'TKL', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(212, 0, 'Tonga', '', 'TO', 'TON', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(213, 0, 'Trinidad and Tobago', '', 'TT', 'TTO', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(214, 0, 'Tunisia', '', 'TN', 'TUN', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(215, 0, 'Turkey', '', 'TR', 'TUR', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(216, 0, 'Turkmenistan', '', 'TM', 'TKM', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(217, 0, 'Turks and Caicos Islands', '', 'TC', 'TCA', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(218, 0, 'Tuvalu', '', 'TV', 'TUV', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(219, 0, 'Uganda', '', 'UG', 'UGA', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(220, 0, 'Ukraine', '', 'UA', 'UKR', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(221, 0, 'United Arab Emirates', '', 'AE', 'ARE', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(222, 0, 'United Kingdom', '', 'GB', 'GBR', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 1, '', '', NOW(), NOW()),
(223, 1, 'United States', '', 'US', 'USA', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(224, 0, 'United States Minor Outlying Islands', '', 'UM', 'UMI', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(225, 0, 'Uruguay', '', 'UY', 'URY', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(226, 0, 'Uzbekistan', '', 'UZ', 'UZB', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(227, 0, 'Vanuatu', '', 'VU', 'VUT', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(228, 0, 'Vatican City State (Holy See)', '', 'VA', 'VAT', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(229, 0, 'Venezuela', '', 'VE', 'VEN', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(230, 0, 'Viet Nam', '', 'VN', 'VNM', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(231, 0, 'Virgin Islands (British)', '', 'VG', 'VGB', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(232, 0, 'Virgin Islands (U.S.)', '', 'VI', 'VIR', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(233, 0, 'Wallis and Futuna Islands', '', 'WF', 'WLF', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(234, 0, 'Western Sahara', '', 'EH', 'ESH', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(235, 0, 'Yemen', '', 'YE', 'YEM', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(236, 0, 'Yugoslavia', '', 'YU', 'YUG', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(237, 0, 'Democratic Republic of Congo', '', 'CD', 'COD', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(238, 0, 'Zambia', '', 'ZM', 'ZMB', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW()),
(239, 0, 'Zimbabwe', '', 'ZW', 'ZWE', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 0, '', '', NOW(), NOW());
-- --------------------------------------------------------
INSERT INTO `lc_languages` (`status`, `code`, `name`, `locale`, `charset`, `raw_date`, `raw_time`, `raw_datetime`, `format_date`, `format_time`, `format_datetime`, `decimal_point`, `thousands_sep`, `priority`, `date_updated`, `date_created`) VALUES
(1, 'en', 'English', 'en_US.utf8', 'UTF-8', 'm/d/y', 'h:i:s A', 'm/d/y h:i:s A', '%b %e %Y', '%I:%M %p', '%b %e %Y %I:%M %p', '.', ',', 0, NOW(), NOW());
-- --------------------------------------------------------
INSERT INTO `lc_settings_groups` (`key`, `name`, `description`, `priority`) VALUES
('store_info', 'Store Info', 'Store information', 10),
('defaults', 'Defaults', 'Store default settings', 20),
('general', 'General', 'Store default settings', 30),
('listings', 'Listings', '', 40),
('checkout', 'Checkout', 'Checkout settings', 50),
('advanced', 'Advanced', 'Advanced settings', 50);
-- --------------------------------------------------------
INSERT INTO `lc_settings` (`setting_group_key`, `type`, `title`, `description`, `key`, `value`, `function`, `priority`, `date_updated`, `date_created`) VALUES
('store_info', 'global', 'Store Name', 'The name of your store.', 'store_name', 'My Store', 'input()', 10, NOW(), NOW()),
('store_info', 'global', 'Store Time Zone', 'The store time zone.', 'store_timezone', 'Europe/Stockholm', 'timezones()', 40, NOW(), NOW()),
('store_info', 'local', 'Tax ID', 'The store tax ID or VATIN.', 'store_tax_id', 'XX000000000000', 'input()', 16, NOW(), NOW()),
('store_info', 'local', 'Postal Address', 'The store postal address.', 'store_postal_address', 'My Store\r\nStreet\r\nPostcode City\r\nCountry', 'bigtext()', 12, NOW(), NOW()),
('store_info', 'global', 'Store Email', 'The store e-mail address.', 'store_email', 'store@mystore.net', 'input()', 11, NOW(), NOW()),
('store_info', 'local', 'Phone Number', 'The store phone number.', 'store_phone', '+46 8-123 45 67', 'input()', 15, NOW(), NOW()),
('store_info', 'global', 'Store Currency', 'The currency of which all prices conform to.', 'store_currency_code', 'EUR', 'currencies()', 31, NOW(), NOW()),
('store_info', 'global', 'Store Country', 'The country of your store.', 'store_country_code', 'SE', 'countries()', 13, NOW(), NOW()),
('store_info', 'global', 'Store Zone', 'The zone of your store.', 'store_zone_code', '', 'zones()', 14, NOW(), NOW()),
('store_info', 'global', 'Store Weight Class', 'The preselected weight class.', 'store_weight_class', 'kg', 'weight_classes()', 32, NOW(), NOW()),
('store_info', 'global', 'Store Length Class', 'The preselected length class.', 'store_length_class', 'cm', 'length_classes()', 33, NOW(), NOW()),
('store_info', 'global', 'Template: Catalog', '', 'store_template_catalog', 'default.catalog', 'templates()', 50, NOW(), NOW()),
('store_info', 'global', 'Template: Admin', '', 'store_template_admin', 'default.admin', 'templates()', 51, NOW(), NOW()),
('defaults', 'global', 'Default Language', 'The default language selected, if failed to identify.', 'default_language_code', 'en', 'languages()', 10, NOW(), NOW()),
('defaults', 'global', 'Default Currency', 'The default currency selected.', 'default_currency_code', 'SEK', 'currencies()', 11, NOW(), NOW()),
('defaults', 'global', 'Default Country', 'The default country selected if not set otherwise.', 'default_country_code', 'SE', 'countries()', 12, NOW(), NOW()),
('defaults', 'global', 'Default Zone', 'The default zone selected if not set otherwise.', 'default_zone_code', '0', 'zones()', 13, NOW(), NOW()),
('defaults', 'local', 'Default Tax Class', 'Default tax class that will be preset when creating new products.', 'default_tax_class_id', '1', 'tax_classes()', 20, NOW(), NOW()),
('general', 'global', 'Set Currency by Language', 'Chain select currency when changing language.', 'set_currency_by_language', 'true', 'toggle()', 10, NOW(), NOW()),
('general', 'local', 'Contact Form CAPTCHA', 'Prevents spam by enabling CAPTCHA in the contact form.', 'contact_form_captcha_enabled', 'false', 'toggle()', 20, NOW(), NOW()),
('listings', 'local', 'Items Per Page', 'The number of items to be displayed per page.', 'items_per_page', '20', 'int()', 20, NOW(), NOW()),
('listings', 'global', 'Display Prices Including Tax', 'Displays all prices in catalog including tax.', 'display_prices_including_tax', 'true', 'toggle()', 10, NOW(), NOW()),
('listings', 'local', 'Data Table Rows', 'The number of data table rows per page.', 'data_table_rows_per_page', '20', 'input()', 50, NOW(), NOW()),
('listings', 'local', 'Display Stock Count', 'Show the available amounts of products in stock.', 'display_stock_count', 'true', 'toggle()', 40, NOW(), NOW()),
('listings', 'local', 'Cheapest Shipping', 'Display the cheapest shipping cost on product page.', 'display_cheapest_shipping', 'true', 'toggle()', 30, NOW(), NOW()),
('checkout', 'local', 'Password Field', 'Show the password field, letting customers set their own password. Otherwise randomly generated.', 'fields_customer_password', 'false', 'toggle()', 11, NOW(), NOW()),
('checkout', 'local', 'Enable AJAX Checkout', 'Enables AJAX functionality for checkout.', 'checkout_ajax_enabled', 'true', 'toggle()', 13, NOW(), NOW()),
('checkout', 'local', 'Register Guests', 'Automatically create accounts for all guests.', 'register_guests', 'false', 'toggle()', 10, NOW(), NOW()),
('checkout', 'local', 'Enable CAPTCHA', 'Lets customers enter a CAPTACHA code before placing orders.', 'checkout_captcha_enabled', 'true', 'toggle()', 12, NOW(), NOW()),
('checkout', 'local', 'Order Copy Receipients', 'Send order copies to the following e-mail addresses. Separate by semi-colons.', 'email_order_copy', 'shop@tim-international.net', 'mediumtext()', 14, NOW(), NOW()),
('advanced', 'global', 'Clear SEO Links Cache', 'Remove all cached SEO links from database.', 'cache_clear_seo_links', 'false', 'toggle()', 11, NOW(), NOW()),
('advanced', 'global', 'Clear Thumbnails Cache', 'Remove all cached image thumnbnails from disk.', 'cache_clear_thumbnails', 'false', 'toggle()', 20, NOW(), NOW()),
('advanced', 'global', 'SEO Links Language Prefix', 'Begins the SEO links with the language code i.e. /en/....', 'seo_links_language_prefix', 'true', 'toggle()', 0, NOW(), NOW()),
('advanced', 'global', 'Regional Settings Screen', 'Enables the regional settings screen upon first visit.', 'regional_settings_screen_enabled', 'true', 'toggle()', 0, NOW(), NOW()),
('advanced', 'global', 'Jobs Last Run', 'Time when background jobs where last executed.', 'jobs_last_run', NOW(), 'input()', 41, NOW(), NOW()),
('advanced', 'global', 'GZIP Enabled', 'Compresses browser data. Increases the load on the server but decreases the bandwidth.', 'gzip_enabled', 'false', 'toggle()', 60, NOW(), NOW()),
('advanced', 'global', 'System Cache Enabled', 'Enables the system cache module which caches frequently used data.', 'cache_enabled', 'true', 'toggle()', 50, NOW(), NOW()),
('advanced', 'local', 'Jobs Interval', 'The amount of minutes between each execution of jobs.', 'jobs_interval', '60', 'int()', 40, NOW(), NOW()),
('advanced', 'local', 'Database Admin Link', 'The URL to your database manager i.e. phpMyAdmin.', 'database_admin_link', 'http://mysql.tim-international.net', 'input()', 30, NOW(), NOW()),
('advanced', 'global', 'SEO Links Enabled', 'Enabling this requires .htaccess and mod_rewrite rules.', 'seo_links_enabled', 'true', 'toggle()', 10, NOW(), NOW()),
('', 'local', 'Installed Job Modules', '', 'jobs_modules', 'job_currency_updater;job_error_reporter', '', 0, NOW(), NOW()),
('', 'local', 'Installed Shipping Modules', '', 'shipping_modules', 'sm_flat_rate;sm_free;sm_weight_table;sm_zone', '', 0, NOW(), NOW()),
('', 'local', 'Installed Payment Modules', '', 'payment_modules', 'pm_cod;pm_invoice;pm_swp_aio;pm_bank_transfer', '', 0, NOW(), NOW()),
('', 'local', 'Installed Order Total Modules', '', 'order_total_modules', 'ot_subtotal;ot_payment_fee;ot_shipping_fee', '', 0, NOW(), NOW()),
('', 'local', 'Installed Get Address Modules', '', 'get_address_modules', 'ga_google_maps', '', 0, NOW(), NOW()),
('', 'local', 'Installed Order Success Modules', '', 'order_success_modules', 'os_google_ecommerce', '', 0, NOW(), NOW()),
('', 'local', '', '', 'shipping_module_sm_free', 'a:5:{s:6:"status";s:7:"Enabled";s:4:"icon";s:0:"";s:14:"minimum_amount";s:4:"0.00";s:11:"geo_zone_id";s:0:"";s:8:"priority";s:1:"0";}', '', 0, NOW(), NOW()),
('', 'local', '', '', 'order_total_module_ot_payment_fee', 'a:1:{s:10:"sort_order";s:2:"10";}', '', 0, NOW(), NOW()),
('', 'local', '', '', 'order_total_module_ot_shipping_fee', 'a:1:{s:10:"sort_order";s:2:"10";}', '', 0, NOW(), NOW()),
('', 'local', '', '', 'order_total_module_ot_subtotal', 'a:1:{s:10:"sort_order";s:1:"1";}', '', 0, NOW(), NOW()),
('', 'local', 'Date Cache Cleared', 'Do not use system cache older than breakpoint.', 'cache_system_breakpoint', NOW(), 'input()', 0, NOW(), NOW());
-- --------------------------------------------------------
INSERT INTO `lc_currencies` (`status`, `code`, `name`, `value`, `decimals`, `prefix`, `suffix`, `priority`, `date_updated`, `date_created`) VALUES
(1, 'EUR', 'Euro', 1, 2, '', ' €', 0, NOW(), NOW());
-- --------------------------------------------------------
INSERT INTO `lc_orders_status` (`id`, `is_sale`, `date_updated`, `date_created`) VALUES
(1, 1, NOW(), NOW()),
(2, 1, NOW(), NOW()),
(3, 1, NOW(), NOW()),
(4, 0, NOW(), NOW()),
(5, 0, NOW(), NOW());
-- --------------------------------------------------------
INSERT INTO `lc_orders_status_info` (`id`, `order_status_id`, `language_code`, `name`, `description`) VALUES
(1, 1, 'en', 'Pending', ''),
(2, 2, 'en', 'Processing', ''),
(3, 3, 'en', 'Completed', ''),
(4, 4, 'en', 'Awaiting payment', ''),
(5, 5, 'en', 'Cancelled', '');
