SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
-- --------------------------------------------------------
INSERT INTO `lc_countries` (`id`, `status`, `name`, `domestic_name`, `iso_code_1`, `iso_code_2`, `iso_code_3`, `tax_id_format`, `address_format`, `postcode_format`, `postcode_required`, `language_code`, `currency_code`, `phone_code`, `date_updated`, `date_created`) VALUES 
(1, 1, 'Afghanistan', '', '004', 'AF', 'AFG', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'fa', 'AFN', '93', NOW(), NOW()),
(2, 1, 'Albania', '', '008', 'AL', 'ALB', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'sq', 'ALL', '355', NOW(), NOW()),
(3, 1, 'Algeria', '', '012', 'DZ', 'DZA', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{5}', 0, 'ar', 'DZD', '213', NOW(), NOW()),
(4, 1, 'American Samoa', '', '016', 'AS', 'ASM', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '96799', 0, 'en', 'USD', '168', NOW(), NOW()),
(5, 1, 'Andorra', '', '020', 'AD', 'AND', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 'AD\\d{3}', 0, 'ca', 'EUR', '376', NOW(), NOW()),
(6, 1, 'Angola', '', '024', 'AO', 'AGO', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'pt', 'AOA', '244', NOW(), NOW()),
(7, 1, 'Anguilla', '', '660', 'AI', 'AIA', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'XCD', '126', NOW(), NOW()),
(8, 1, 'Antarctica', '', '010', 'AQ', 'ATA', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, '', 'XCD', '672', NOW(), NOW()),
(9, 1, 'Antigua and Barbuda', '', '028', 'AG', 'ATG', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'XCD', '126', NOW(), NOW()),
(10, 1, 'Argentina', '', '032', 'AR', 'ARG', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '([A-HJ-NP-Z])?\\d{4}([A-Z]{3})?', 0, 'es', 'ARS', '54', NOW(), NOW()),
(11, 1, 'Armenia', '', '051', 'AM', 'ARM', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '(37)?\\d{4}', 0, 'hy', 'AMD', '374', NOW(), NOW()),
(12, 1, 'Aruba', '', '533', 'AW', 'ABW', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'nl', 'AWG', '297', NOW(), NOW()),
(13, 1, 'Australia', '', '036', 'AU', 'AUS', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{4}', 0, 'en', 'AUD', '61', NOW(), NOW()),
(14, 1, 'Austria', '', '040', 'AT', 'AUT', '^(AT)?(U[A-Zd]{8})$', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{4}', 0, 'de', 'EUR', '43', NOW(), NOW()),
(15, 1, 'Azerbaijan', '', '031', 'AZ', 'AZE', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{4}', 0, 'az', 'AZN', '994', NOW(), NOW()),
(16, 1, 'Bahamas', '', '044', 'BS', 'BHS', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'BSD', '124', NOW(), NOW()),
(17, 1, 'Bahrain', '', '048', 'BH', 'BHR', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '((1[0-2]|[2-9])\\d{2})?', 0, 'ar', 'BHD', '973', NOW(), NOW()),
(18, 1, 'Bangladesh', '', '050', 'BD', 'BGD', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{4}', 0, 'bn', 'BDT', '880', NOW(), NOW()),
(19, 1, 'Barbados', '', '052', 'BB', 'BRB', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '(BB\\d{5})?', 0, 'en', 'BBD', '124', NOW(), NOW()),
(20, 1, 'Belarus', '', '112', 'BY', 'BLR', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{6}', 0, 'be', 'BYR', '375', NOW(), NOW()),
(21, 1, 'Belgium', '', '056', 'BE', 'BEL', '^(BE)?(0)?(d{9})$', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{4}', 0, 'nl', 'EUR', '32', NOW(), NOW()),
(22, 1, 'Belize', '', '084', 'BZ', 'BLZ', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'BZD', '501', NOW(), NOW()),
(23, 1, 'Benin', '', '204', 'BJ', 'BEN', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'fr', 'XOF', '229', NOW(), NOW()),
(24, 1, 'Bermuda', '', '060', 'BM', 'BMU', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[A-Z]{2}[ ]?[A-Z0-9]{2}', 0, 'en', 'BMD', '144', NOW(), NOW()),
(25, 1, 'Bhutan', '', '064', 'BT', 'BTN', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'dz', 'BTN', '975', NOW(), NOW()),
(26, 1, 'Bolivia', '', '068', 'BO', 'BOL', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'es', 'BOB', '591', NOW(), NOW()),
(27, 1, 'Bosnia and Herzegowina', '', '070', 'BA', 'BIH', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{5}', 0, 'bs', 'BAM', '387', NOW(), NOW()),
(28, 1, 'Botswana', '', '072', 'BW', 'BWA', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'BWP', '267', NOW(), NOW()),
(29, 1, 'Bouvet Island', '', '074', 'BV', 'BVT', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, '', 'NOK', '47', NOW(), NOW()),
(30, 1, 'Brazil', '', '076', 'BR', 'BRA', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{5}[\\-]?\\d{3}', 0, 'pt', 'BRL', '55', NOW(), NOW()),
(31, 1, 'British Indian Ocean Territory', '', '086', 'IO', 'IOT', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 'BBND 1ZZ', 0, 'en', 'USD', '246', NOW(), NOW()),
(32, 1, 'Brunei Darussalam', '', '096', 'BN', 'BRN', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[A-Z]{2}[ ]?\\d{4}', 0, 'ms', 'BND', '673', NOW(), NOW()),
(33, 1, 'Bulgaria', '', '100', 'BG', 'BGR', '^(BG)?(d{9,10})$', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{4}', 0, 'bg', 'BGN', '359', NOW(), NOW()),
(34, 1, 'Burkina Faso', '', '854', 'BF', 'BFA', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'fr', 'XOF', '226', NOW(), NOW()),
(35, 1, 'Burundi', '', '108', 'BI', 'BDI', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'fr', 'BIF', '257', NOW(), NOW()),
(36, 1, 'Cambodia', '', '116', 'KH', 'KHM', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{5}', 0, 'km', 'KHR', '855', NOW(), NOW()),
(37, 1, 'Cameroon', '', '120', 'CM', 'CMR', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'XAF', '237', NOW(), NOW()),
(38, 1, 'Canada', '', '124', 'CA', 'CAN', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[ABCEGHJKLMNPRSTVXY]\\d[ABCEGHJ-NPRSTV-Z][ ]?\\d[ABCEGHJ-NPRSTV-Z]\\d', 0, 'en', 'CAD', '1', NOW(), NOW()),
(39, 1, 'Cape Verde', '', '132', 'CV', 'CPV', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{4}', 0, 'pt', 'CVE', '238', NOW(), NOW()),
(40, 1, 'Cayman Islands', '', '136', 'KY', 'CYM', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'KYD', '134', NOW(), NOW()),
(41, 1, 'Central African Republic', '', '140', 'CF', 'CAF', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'fr', 'XAF', '236', NOW(), NOW()),
(42, 1, 'Chad', '', '148', 'TD', 'TCD', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'fr', 'XAF', '235', NOW(), NOW()),
(43, 1, 'Chile', '', '152', 'CL', 'CHL', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'es', 'CLP', '56', NOW(), NOW()),
(44, 1, 'China', '', '156', 'CN', 'CHN', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{6}', 0, 'zh', 'CNY', '86', NOW(), NOW()),
(45, 1, 'Christmas Island', '', '162', 'CX', 'CXR', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '6798', 0, 'en', 'AUD', '61', NOW(), NOW()),
(46, 1, 'Cocos (Keeling) Islands', '', '166', 'CC', 'CCK', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '6799', 0, 'ms', 'AUD', '61', NOW(), NOW()),
(47, 1, 'Colombia', '', '170', 'CO', 'COL', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'es', 'COP', '57', NOW(), NOW()),
(48, 1, 'Comoros', '', '174', 'KM', 'COM', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'ar', 'KMF', '269', NOW(), NOW()),
(49, 1, 'Congo', '', '178', 'CG', 'COG', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'fr', 'XAF', '242', NOW(), NOW()),
(50, 1, 'Cook Islands', '', '184', 'CK', 'COK', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{4}', 0, 'en', 'NZD', '682', NOW(), NOW()),
(51, 1, 'Costa Rica', '', '188', 'CR', 'CRI', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{4,5}|\\d{3}-\\d{4}', 0, 'es', 'CRC', '506', NOW(), NOW()),
(52, 1, 'Cote D\'Ivoire', '', '384', 'CI', 'CIV', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'fr', 'XOF', '225', NOW(), NOW()),
(53, 1, 'Croatia', '', '191', 'HR', 'HRV', '^(HR)?(d{11})$', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{5}', 0, 'hr', 'HRK', '385', NOW(), NOW()),
(54, 1, 'Cuba', '', '192', 'CU', 'CUB', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'es', 'CUP', '53', NOW(), NOW()),
(55, 1, 'Cyprus', '', '196', 'CY', 'CYP', '^(CY)?(d{8}[A-Z]{1})$', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{4}', 0, 'el', 'EUR', '357', NOW(), NOW()),
(56, 1, 'Czech Republic', '', '203', 'CZ', 'CZE', '^(CZ)?(d{8,10})$', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{3}[ ]?\\d{2}', 0, 'cs', 'CZK', '420', NOW(), NOW()),
(57, 1, 'Denmark', '', '208', 'DK', 'DNK', '^(DK)?(d{8})$', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{4}', 0, 'da', 'DKK', '45', NOW(), NOW()),
(58, 1, 'Djibouti', '', '262', 'DJ', 'DJI', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'fr', 'DJF', '253', NOW(), NOW()),
(59, 1, 'Dominica', '', '212', 'DM', 'DMA', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'XCD', '176', NOW(), NOW()),
(60, 1, 'Dominican Republic', '', '214', 'DO', 'DOM', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{5}', 0, 'es', 'DOP', '180', NOW(), NOW()),
(61, 1, 'East Timor', '', '626', 'TP', 'TMP', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, '', 'USD', '670', NOW(), NOW()),
(62, 1, 'Ecuador', '', '218', 'EC', 'ECU', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '([A-Z]\\d{4}[A-Z]|(?:[A-Z]{2})?\\d{6})?', 0, 'es', 'ECS', '593', NOW(), NOW()),
(63, 1, 'Egypt', '', '818', 'EG', 'EGY', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{5}', 0, 'ar', 'EGP', '20', NOW(), NOW()),
(64, 1, 'El Salvador', '', '222', 'SV', 'SLV', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'es', 'SVC', '503', NOW(), NOW()),
(65, 1, 'Equatorial Guinea', '', '226', 'GQ', 'GNQ', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'es', 'XAF', '240', NOW(), NOW()),
(66, 1, 'Eritrea', '', '232', 'ER', 'ERI', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'aa', 'ERN', '291', NOW(), NOW()),
(67, 1, 'Estonia', '', '233', 'EE', 'EST', '^(EE)?(d{9})$', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{5}', 0, 'et', 'EUR', '372', NOW(), NOW()),
(68, 1, 'Ethiopia', '', '231', 'ET', 'ETH', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{4}', 0, 'am', 'ETB', '251', NOW(), NOW()),
(69, 1, 'Falkland Islands (Malvinas)', '', '238', 'FK', 'FLK', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 'FIQQ 1ZZ', 0, 'en', 'FKP', '500', NOW(), NOW()),
(70, 1, 'Faroe Islands', '', '234', 'FO', 'FRO', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{3}', 0, 'fo', 'DKK', '298', NOW(), NOW()),
(71, 1, 'Fiji', '', '242', 'FJ', 'FJI', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'FJD', '679', NOW(), NOW()),
(72, 1, 'Finland', '', '246', 'FI', 'FIN', '^(FI)?(d{8})$', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{5}', 0, 'fi', 'EUR', '358', NOW(), NOW()),
(73, 1, 'France', '', '250', 'FR', 'FRA', '^(FR)?(([A-Z]{2}|d{2})d{9})$', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{2}[ ]?\\d{3}', 0, 'fr', 'EUR', '33', NOW(), NOW()),
(75, 1, 'French Guiana', '', '254', 'GF', 'GUF', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '9[78]3\\d{2}', 0, 'fr', 'EUR', '594', NOW(), NOW()),
(76, 1, 'French Polynesia', '', '258', 'PF', 'PYF', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '987\\d{2}', 0, 'fr', 'XPF', '689', NOW(), NOW()),
(77, 1, 'French Southern Territories', '', '260', 'TF', 'ATF', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'fr', 'EUR', '262', NOW(), NOW()),
(78, 1, 'Gabon', '', '266', 'GA', 'GAB', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'fr', 'XAF', '241', NOW(), NOW()),
(79, 1, 'Gambia', '', '270', 'GM', 'GMB', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'GMD', '220', NOW(), NOW()),
(80, 1, 'Georgia', '', '268', 'GE', 'GEO', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{4}', 0, 'ka', 'GEL', '995', NOW(), NOW()),
(81, 1, 'Germany', '', '276', 'DE', 'DEU', '^(DE)?(d{9})$', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{5}', 0, 'de', 'EUR', '49', NOW(), NOW()),
(82, 1, 'Ghana', '', '288', 'GH', 'GHA', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'GHS', '233', NOW(), NOW()),
(83, 1, 'Gibraltar', '', '292', 'GI', 'GIB', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'GIP', '350', NOW(), NOW()),
(84, 1, 'Greece', '', '300', 'GR', 'GRC', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{3}[ ]?\\d{2}', 0, 'el', 'EUR', '30', NOW(), NOW()),
(85, 1, 'Greenland', '', '304', 'GL', 'GRL', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '39\\d{2}', 0, 'kl', 'DKK', '299', NOW(), NOW()),
(86, 1, 'Grenada', '', '308', 'GD', 'GRD', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'XCD', '147', NOW(), NOW()),
(87, 1, 'Guadeloupe', '', '312', 'GP', 'GLP', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '9[78][01]\\d{2}', 0, 'fr', 'EUR', '590', NOW(), NOW()),
(88, 1, 'Guam', '', '316', 'GU', 'GUM', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '969[123]\\d([ \\-]\\d{4})?', 0, 'en', 'USD', '167', NOW(), NOW()),
(89, 1, 'Guatemala', '', '320', 'GT', 'GTM', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{5}', 0, 'es', 'QTQ', '502', NOW(), NOW()),
(90, 1, 'Guinea', '', '324', 'GN', 'GIN', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{3}', 0, 'fr', 'GNF', '224', NOW(), NOW()),
(91, 1, 'Guinea-bissau', '', '624', 'GW', 'GNB', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{4}', 0, 'pt', 'GWP', '245', NOW(), NOW()),
(92, 1, 'Guyana', '', '328', 'GY', 'GUY', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'GYD', '592', NOW(), NOW()),
(93, 1, 'Haiti', '', '332', 'HT', 'HTI', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{4}', 0, 'ht', 'HTG', '509', NOW(), NOW()),
(94, 1, 'Heard and McDonald Islands', '', '334', 'HM', 'HMD', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{4}', 0, '', 'AUD', '0', NOW(), NOW()),
(95, 1, 'Honduras', '', '340', 'HN', 'HND', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '(?:\\d{5})?', 0, 'es', 'HNL', '504', NOW(), NOW()),
(96, 1, 'Hong Kong', '', '344', 'HK', 'HKG', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'zh', 'HKD', '852', NOW(), NOW()),
(97, 1, 'Hungary', '', '348', 'HU', 'HUN', '^(HU)?(d{8})$', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{4}', 0, 'hu', 'HUF', '36', NOW(), NOW()),
(98, 1, 'Iceland', '', '352', 'IS', 'ISL', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{3}', 0, 'is', 'ISK', '354', NOW(), NOW()),
(99, 1, 'India', '', '356', 'IN', 'IND', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{6}', 0, 'en', 'INR', '91', NOW(), NOW()),
(100, 1, 'Indonesia', '', '360', 'ID', 'IDN', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{5}', 0, 'id', 'IDR', '62', NOW(), NOW()),
(101, 1, 'Iran, Islamic Republic of', '', '364', 'IR', 'IRN', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'fa', 'IRR', '98', NOW(), NOW()),
(102, 1, 'Iraq', '', '368', 'IQ', 'IRQ', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{5}', 0, 'ar', 'IQD', '964', NOW(), NOW()),
(103, 1, 'Ireland', '', '372', 'IE', 'IRL', '^(IE)?(d{7}[A-Z]{2})$', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'EUR', '353', NOW(), NOW()),
(104, 1, 'Israel', '', '376', 'IL', 'ISR', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{5}', 0, 'he', 'ILS', '972', NOW(), NOW()),
(105, 1, 'Italy', '', '380', 'IT', 'ITA', '^(IT)?(d{11})$', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{5}', 0, 'it', 'EUR', '39', NOW(), NOW()),
(106, 1, 'Jamaica', '', '388', 'JM', 'JAM', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'JMD', '187', NOW(), NOW()),
(107, 1, 'Japan', '', '392', 'JP', 'JPN', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{3}-\\d{4}', 0, 'ja', 'JPY', '81', NOW(), NOW()),
(108, 1, 'Jordan', '', '400', 'JO', 'JOR', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{5}', 0, 'ar', 'JOD', '962', NOW(), NOW()),
(109, 1, 'Kazakhstan', '', '398', 'KZ', 'KAZ', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{6}', 0, 'kk', 'KZT', '7', NOW(), NOW()),
(110, 1, 'Kenya', '', '404', 'KE', 'KEN', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{5}', 0, 'en', 'KES', '254', NOW(), NOW()),
(111, 1, 'Kiribati', '', '296', 'KI', 'KIR', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'AUD', '686', NOW(), NOW()),
(112, 1, 'North Korea', '', '408', 'KP', 'PRK', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'ko', 'KPW', '850', NOW(), NOW()),
(113, 1, 'Korea, Republic of', '', '410', 'KR', 'KOR', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{3}[\\-]\\d{3}', 0, 'ko', 'KRW', '82', NOW(), NOW()),
(114, 1, 'Kuwait', '', '414', 'KW', 'KWT', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{5}', 0, 'ar', 'KWD', '965', NOW(), NOW()),
(115, 1, 'Kyrgyzstan', '', '417', 'KG', 'KGZ', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{6}', 0, 'ky', 'KGS', '996', NOW(), NOW()),
(116, 1, 'Lao People\'s Democratic Republic', '', '418', 'LA', 'LAO', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{5}', 0, 'lo', 'LAK', '856', NOW(), NOW()),
(117, 1, 'Latvia', '', '428', 'LV', 'LVA', '^(LV)?(d{11})$', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{4}', 0, 'lv', 'LVL', '371', NOW(), NOW()),
(118, 1, 'Lebanon', '', '422', 'LB', 'LBN', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '(\\d{4}([ ]?\\d{4})?)?', 0, 'ar', 'LBP', '961', NOW(), NOW()),
(119, 1, 'Lesotho', '', '426', 'LS', 'LSO', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{3}', 0, 'en', 'LSL', '266', NOW(), NOW()),
(120, 1, 'Liberia', '', '430', 'LR', 'LBR', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{4}', 0, 'en', 'LRD', '231', NOW(), NOW()),
(121, 1, 'Libyan Arab Jamahiriya', '', '434', 'LY', 'LBY', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'ar', 'LYD', '218', NOW(), NOW()),
(122, 1, 'Liechtenstein', '', '438', 'LI', 'LIE', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '(948[5-9])|(949[0-7])', 0, 'de', 'CHF', '423', NOW(), NOW()),
(123, 1, 'Lithuania', '', '440', 'LT', 'LTU', '^(LT)?((d{9}|d{12}))$', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{5}', 0, 'lt', 'LTL', '370', NOW(), NOW()),
(124, 1, 'Luxembourg', '', '442', 'LU', 'LUX', '^(LU)?(d{8})$', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{4}', 0, 'lb', 'EUR', '352', NOW(), NOW()),
(125, 1, 'Macau', '', '446', 'MO', 'MAC', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'zh', 'MOP', '853', NOW(), NOW()),
(126, 1, 'Macedonia', '', '807', 'MK', 'MKD', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{4}', 0, 'mk', 'MKD', '389', NOW(), NOW()),
(127, 1, 'Madagascar', '', '450', 'MG', 'MDG', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{3}', 0, 'fr', 'MGF', '261', NOW(), NOW()),
(128, 1, 'Malawi', '', '454', 'MW', 'MWI', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'ny', 'MWK', '265', NOW(), NOW()),
(129, 1, 'Malaysia', '', '458', 'MY', 'MYS', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{5}', 0, 'ms', 'MYR', '60', NOW(), NOW()),
(130, 1, 'Maldives', '', '462', 'MV', 'MDV', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{5}', 0, 'dv', 'MVR', '960', NOW(), NOW()),
(131, 1, 'Mali', '', '466', 'ML', 'MLI', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'fr', 'XOF', '223', NOW(), NOW()),
(132, 1, 'Malta', '', '470', 'MT', 'MLT', '^(MT)?(d{8})$', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'mt', 'EUR', '356', NOW(), NOW()),
(133, 1, 'Marshall Islands', '', '584', 'MH', 'MHL', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '969[67]\\d([ \\-]\\d{4})?', 0, 'mh', 'USD', '692', NOW(), NOW()),
(134, 1, 'Martinique', '', '474', 'MQ', 'MTQ', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '9[78]2\\d{2}', 0, 'fr', 'EUR', '596', NOW(), NOW()),
(135, 1, 'Mauritania', '', '478', 'MR', 'MRT', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'ar', 'MRO', '222', NOW(), NOW()),
(136, 1, 'Mauritius', '', '480', 'MU', 'MUS', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '(\\d{3}[A-Z]{2}\\d{3})?', 0, 'en', 'MUR', '230', NOW(), NOW()),
(137, 1, 'Mayotte', '', '175', 'YT', 'MYT', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '976\\d{2}', 0, 'fr', 'EUR', '262', NOW(), NOW()),
(138, 1, 'Mexico', '', '484', 'MX', 'MEX', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{5}', 0, 'es', 'MXN', '52', NOW(), NOW()),
(139, 1, 'Micronesia, Federated States of', '', '583', 'FM', 'FSM', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '(9694[1-4])([ \\-]\\d{4})?', 0, 'en', 'USD', '691', NOW(), NOW()),
(140, 1, 'Moldova, Republic of', '', '498', 'MD', 'MDA', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{4}', 0, 'ro', 'MDL', '373', NOW(), NOW()),
(141, 1, 'Monaco', '', '492', 'MC', 'MCO', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '980\\d{2}', 0, 'fr', 'EUR', '377', NOW(), NOW()),
(142, 1, 'Mongolia', '', '496', 'MN', 'MNG', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{6}', 0, 'mn', 'MNT', '976', NOW(), NOW()),
(143, 1, 'Montserrat', '', '500', 'MS', 'MSR', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'XCD', '166', NOW(), NOW()),
(144, 1, 'Morocco', '', '504', 'MA', 'MAR', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{5}', 0, 'ar', 'MAD', '212', NOW(), NOW()),
(145, 1, 'Mozambique', '', '508', 'MZ', 'MOZ', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'pt', 'MZN', '258', NOW(), NOW()),
(146, 1, 'Myanmar', '', '104', 'MM', 'MMR', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'my', 'MMK', '95', NOW(), NOW()),
(147, 1, 'Namibia', '', '516', 'NA', 'NAM', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'NAD', '264', NOW(), NOW()),
(148, 1, 'Nauru', '', '520', 'NR', 'NRU', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'na', 'AUD', '674', NOW(), NOW()),
(149, 1, 'Nepal', '', '524', 'NP', 'NPL', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{5}', 0, 'ne', 'NPR', '977', NOW(), NOW()),
(150, 1, 'Netherlands', '', '528', 'NL', 'NLD', '^(NL)?(d{9}Bd{2})$', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[0-9]{4}', 0, 'nl', 'EUR', '31', NOW(), NOW()),
(151, 1, 'Netherlands Antilles', '', '530', 'AN', 'ANT', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'nl', 'ANG', '599', NOW(), NOW()),
(152, 1, 'New Caledonia', '', '540', 'NC', 'NCL', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '988\\d{2}', 0, 'fr', 'XPF', '687', NOW(), NOW()),
(153, 1, 'New Zealand', '', '554', 'NZ', 'NZL', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{4}', 0, 'en', 'NZD', '64', NOW(), NOW()),
(154, 1, 'Nicaragua', '', '558', 'NI', 'NIC', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '((\\d{4}-)?\\d{3}-\\d{3}(-\\d{1})?)?', 0, 'es', 'NIO', '505', NOW(), NOW()),
(155, 1, 'Niger', '', '562', 'NE', 'NER', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{4}', 0, 'fr', 'XOF', '227', NOW(), NOW()),
(156, 1, 'Nigeria', '', '566', 'NG', 'NGA', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '(\\d{6})?', 0, 'en', 'NGN', '234', NOW(), NOW()),
(157, 1, 'Niue', '', '570', 'NU', 'NIU', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'NZD', '683', NOW(), NOW()),
(158, 1, 'Norfolk Island', '', '574', 'NF', 'NFK', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '2899', 0, 'en', 'AUD', '672', NOW(), NOW()),
(159, 1, 'Northern Mariana Islands', '', '580', 'MP', 'MNP', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '9695[012]([ \\-]\\d{4})?', 0, 'tl', 'USD', '167', NOW(), NOW()),
(160, 1, 'Norway', '', '578', 'NO', 'NOR', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{4}', 0, 'no', 'NOK', '47', NOW(), NOW()),
(161, 1, 'Oman', '', '512', 'OM', 'OMN', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '(PC )?\\d{3}', 0, 'ar', 'OMR', '968', NOW(), NOW()),
(162, 1, 'Pakistan', '', '586', 'PK', 'PAK', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{5}', 0, 'ur', 'PKR', '92', NOW(), NOW()),
(163, 1, 'Palau', '', '585', 'PW', 'PLW', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '96940', 0, 'en', 'USD', '680', NOW(), NOW()),
(164, 1, 'Panama', '', '591', 'PA', 'PAN', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'es', 'PAB', '507', NOW(), NOW()),
(165, 1, 'Papua New Guinea', '', '598', 'PG', 'PNG', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{3}', 0, 'en', 'PGK', '675', NOW(), NOW()),
(166, 1, 'Paraguay', '', '600', 'PY', 'PRY', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{4}', 0, 'es', 'PYG', '595', NOW(), NOW()),
(167, 1, 'Peru', '', '604', 'PE', 'PER', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'es', 'PEN', '51', NOW(), NOW()),
(168, 1, 'Philippines', '', '608', 'PH', 'PHL', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{4}', 0, 'tl', 'PHP', '63', NOW(), NOW()),
(169, 1, 'Pitcairn', '', '612', 'PN', 'PCN', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 'PCRN 1ZZ', 0, 'en', 'NZD', '870', NOW(), NOW()),
(170, 1, 'Poland', '', '616', 'PL', 'POL', '^(PL)?(d{10})$', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{2}-\\d{3}', 0, 'pl', 'PLN', '48', NOW(), NOW()),
(171, 1, 'Portugal', '', '620', 'PT', 'PRT', '^(PT)?(d{9})$', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{4}([\\-]\\d{3})?', 0, 'pt', 'EUR', '351', NOW(), NOW()),
(172, 1, 'Puerto Rico', '', '630', 'PR', 'PRI', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '00[679]\\d{2}([ \\-]\\d{4})?', 0, 'en', 'USD', '1', NOW(), NOW()),
(173, 1, 'Qatar', '', '634', 'QA', 'QAT', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'ar', 'QAR', '974', NOW(), NOW()),
(174, 1, 'Reunion', '', '638', 'RE', 'REU', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '9[78]4\\d{2}', 0, 'fr', 'EUR', '262', NOW(), NOW()),
(175, 1, 'Romania', '', '642', 'RO', 'ROM', '^(RO)?(d{2,10})$', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{6}', 0, 'ro', 'RON', '40', NOW(), NOW()),
(176, 1, 'Russian Federation', '', '643', 'RU', 'RUS', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{6}', 0, 'ru', 'RUB', '7', NOW(), NOW()),
(177, 1, 'Rwanda', '', '646', 'RW', 'RWA', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'rw', 'RWF', '250', NOW(), NOW()),
(178, 1, 'Saint Kitts and Nevis', '', '659', 'KN', 'KNA', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'XCD', '186', NOW(), NOW()),
(179, 1, 'Saint Lucia', '', '662', 'LC', 'LCA', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'XCD', '175', NOW(), NOW()),
(180, 1, 'Saint Vincent and the Grenadines', '', '670', 'VC', 'VCT', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'XCD', '178', NOW(), NOW()),
(181, 1, 'Samoa', '', '882', 'WS', 'WSM', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'sm', 'WST', '685', NOW(), NOW()),
(182, 1, 'San Marino', '', '674', 'SM', 'SMR', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '4789\\d', 0, 'it', 'EUR', '378', NOW(), NOW()),
(183, 1, 'Sao Tome and Principe', '', '678', 'ST', 'STP', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'pt', 'STD', '239', NOW(), NOW()),
(184, 1, 'Saudi Arabia', '', '682', 'SA', 'SAU', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{5}', 0, 'ar', 'SAR', '966', NOW(), NOW()),
(185, 1, 'Senegal', '', '686', 'SN', 'SEN', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{5}', 0, 'fr', 'XOF', '221', NOW(), NOW()),
(186, 1, 'Seychelles', '', '690', 'SC', 'SYC', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'SCR', '248', NOW(), NOW()),
(187, 1, 'Sierra Leone', '', '694', 'SL', 'SLE', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'SLL', '232', NOW(), NOW()),
(188, 1, 'Singapore', '', '702', 'SG', 'SGP', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{6}', 0, 'en', 'SGD', '65', NOW(), NOW()),
(189, 1, 'Slovak Republic', '', '703', 'SK', 'SVK', '^(SK)?(d{10})$', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{3}[ ]?\\d{2}', 0, 'sk', 'EUR', '421', NOW(), NOW()),
(190, 1, 'Slovenia', '', '705', 'SI', 'SVN', '^(SI)?(d{8})$', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{4}', 0, 'sl', 'EUR', '386', NOW(), NOW()),
(191, 1, 'Solomon Islands', '', '090', 'SB', 'SLB', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'SBD', '677', NOW(), NOW()),
(192, 1, 'Somalia', '', '706', 'SO', 'SOM', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{5}', 0, 'so', 'SOS', '252', NOW(), NOW()),
(193, 1, 'South Africa', '', '710', 'ZA', 'ZAF', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{4}', 0, 'zu', 'ZAR', '27', NOW(), NOW()),
(194, 1, 'South Georgia and South Sandwich Islands', '', '239', 'GS', 'SGS', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 'SIQQ 1ZZ', 0, 'en', 'GBP', '500', NOW(), NOW()),
(195, 1, 'Spain', '', '724', 'ES', 'ESP', '^(ES)?([A-Z]d{7}[A-Z]|d{8}[A-Z]|[A-Z]d{8})$', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{5}', 0, 'es', 'EUR', '34', NOW(), NOW()),
(196, 1, 'Sri Lanka', '', '144', 'LK', 'LKA', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{5}', 0, 'si', 'LKR', '94', NOW(), NOW()),
(197, 1, 'St. Helena', '', '654', 'SH', 'SHN', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '(ASCN|STHL) 1ZZ', 0, 'en', 'SHP', '290', NOW(), NOW()),
(198, 1, 'St. Pierre and Miquelon', '', '666', 'PM', 'SPM', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '9[78]5\\d{2}', 0, 'fr', 'EUR', '508', NOW(), NOW()),
(199, 1, 'Sudan', '', '729', 'SD', 'SDN', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'ar', 'SDG', '249', NOW(), NOW()),
(200, 1, 'Suriname', '', '740', 'SR', 'SUR', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'nl', 'SRD', '597', NOW(), NOW()),
(201, 1, 'Svalbard and Jan Mayen Islands', '', '744', 'SJ', 'SJM', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{4}', 0, 'no', 'NOK', '47', NOW(), NOW()),
(202, 1, 'Swaziland', '', '748', 'SZ', 'SWZ', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '[HLMS]\\d{3}', 0, 'en', 'SZL', '268', NOW(), NOW()),
(203, 1, 'Sweden', '', '752', 'SE', 'SWE', '^(SE)?(16|19|20)?([0-9]{6})(?:-)?([0-9]{4})?(01)?$', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{3}[ ]?\\d{2}', 0, 'sv', 'SEK', '46', NOW(), NOW()),
(204, 1, 'Switzerland', '', '756', 'CH', 'CHE', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{4}', 0, 'de', 'CHF', '41', NOW(), NOW()),
(205, 1, 'Syrian Arab Republic', '', '760', 'SY', 'SYR', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'ar', 'SYP', '963', NOW(), NOW()),
(206, 1, 'Taiwan', '', '158', 'TW', 'TWN', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{3}(\\d{2})?', 0, 'zh', 'TWD', '886', NOW(), NOW()),
(207, 1, 'Tajikistan', '', '762', 'TJ', 'TJK', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{6}', 0, 'tg', 'TJS', '992', NOW(), NOW()),
(208, 1, 'Tanzania, United Republic of', '', '834', 'TZ', 'TZA', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'sw', 'TZS', '255', NOW(), NOW()),
(209, 1, 'Thailand', '', '764', 'TH', 'THA', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{5}', 0, 'th', 'THB', '66', NOW(), NOW()),
(210, 1, 'Togo', '', '768', 'TG', 'TGO', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'fr', 'XOF', '228', NOW(), NOW()),
(211, 1, 'Tokelau', '', '772', 'TK', 'TKL', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'NZD', '690', NOW(), NOW()),
(212, 1, 'Tonga', '', '776', 'TO', 'TON', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'to', 'TOP', '676', NOW(), NOW()),
(213, 1, 'Trinidad and Tobago', '', '780', 'TT', 'TTO', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'TTD', '186', NOW(), NOW()),
(214, 1, 'Tunisia', '', '788', 'TN', 'TUN', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{4}', 0, 'ar', 'TND', '216', NOW(), NOW()),
(215, 1, 'Turkey', '', '792', 'TR', 'TUR', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{5}', 0, 'tr', 'TRY', '90', NOW(), NOW()),
(216, 1, 'Turkmenistan', '', '795', 'TM', 'TKM', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{6}', 0, 'tk', 'TMT', '993', NOW(), NOW()),
(217, 1, 'Turks and Caicos Islands', '', '796', 'TC', 'TCA', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 'TKCA 1ZZ', 0, 'en', 'USD', '164', NOW(), NOW()),
(218, 1, 'Tuvalu', '', '798', 'TV', 'TUV', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'AUD', '688', NOW(), NOW()),
(219, 1, 'Uganda', '', '800', 'UG', 'UGA', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'UGX', '256', NOW(), NOW()),
(220, 1, 'Ukraine', '', '804', 'UA', 'UKR', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{5}', 0, 'uk', 'UAH', '380', NOW(), NOW()),
(221, 1, 'United Arab Emirates', '', '784', 'AE', 'ARE', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'ar', 'AED', '971', NOW(), NOW()),
(222, 1, 'United Kingdom', '', '826', 'GB', 'GBR', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', 'GIR[ ]?0AA|((AB|AL|B|BA|BB|BD|BH|BL|BN|BR|BS|BT|CA|CB|CF|CH|CM|CO|CR|CT|CV|CW|DA|DD|DE|DG|DH|DL|DN|DT|DY|E|EC|EH|EN|EX|FK|FY|G|GL|GY|GU|HA|HD|HG|HP|HR|HS|HU|HX|IG|IM|IP|IV|JE|KA|KT|KW|KY|L|LA|LD|LE|LL|LN|LS|LU|M|ME|MK|ML|N|NE|NG|NN|NP|NR|NW|OL|OX|PA|PE|PH|PL|PO|PR|RG|RH|RM|S|SA|SE|SG|SK|SL|SM|SN|SO|SP|SR|SS|ST|SW|SY|TA|TD|TF|TN|TQ|TR|TS|TW|UB|W|WA|WC|WD|WF|WN|WR|WS|WV|YO|ZE)(\\d[\\dA-Z]?[ ]?\\d[ABD-HJLN-UW-Z]{2}))|BFPO[ ]?\\d{1,4}', 1, 'en', 'GBP', '44', NOW(), NOW()),
(223, 1, 'United States', '', '840', 'US', 'USA', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{5}([ \\-]\\d{4})?', 0, 'en', 'USD', '1', NOW(), NOW()),
(224, 1, 'United States Minor Outlying Islands', '', '581', 'UM', 'UMI', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'USD', '1', NOW(), NOW()),
(225, 1, 'Uruguay', '', '858', 'UY', 'URY', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{5}', 0, 'es', 'UYU', '598', NOW(), NOW()),
(226, 1, 'Uzbekistan', '', '860', 'UZ', 'UZB', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{6}', 0, 'uz', 'UZS', '998', NOW(), NOW()),
(227, 1, 'Vanuatu', '', '548', 'VU', 'VUT', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'bi', 'VUV', '678', NOW(), NOW()),
(228, 1, 'Vatican City State (Holy See)', '', '336', 'VA', 'VAT', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '00120', 0, 'la', 'EUR', '39', NOW(), NOW()),
(229, 1, 'Venezuela', '', '862', 'VE', 'VEN', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{4}', 0, 'es', 'VEF', '58', NOW(), NOW()),
(230, 1, 'Viet Nam', '', '704', 'VN', 'VNM', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'vi', 'VND', '84', NOW(), NOW()),
(231, 1, 'Virgin Islands (British)', '', '092', 'VG', 'VGB', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'USD', '128', NOW(), NOW()),
(232, 1, 'Virgin Islands (U.S.)', '', '850', 'VI', 'VIR', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '008(([0-4]\\d)|(5[01]))([ \\-]\\d{4})?', 0, 'en', 'USD', '134', NOW(), NOW()),
(233, 1, 'Wallis and Futuna Islands', '', '876', 'WF', 'WLF', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '986\\d{2}', 0, 'fr', 'XPF', '681', NOW(), NOW()),
(234, 1, 'Western Sahara', '', '732', 'EH', 'ESH', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'ar', 'MAD', '212', NOW(), NOW()),
(235, 1, 'Yemen', '', '887', 'YE', 'YEM', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'ar', 'YER', '967', NOW(), NOW()),
(236, 1, 'Serbia', '', '381', 'RS', 'SRB', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'sr', 'RSD', '381', NOW(), NOW()),
(237, 1, 'Democratic Republic of Congo', '', '180', 'CD', 'COD', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'fr', 'XAF', '243', NOW(), NOW()),
(238, 1, 'Zambia', '', '894', 'ZM', 'ZMB', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '\\d{5}', 0, 'en', 'ZMW', '260', NOW(), NOW()),
(239, 1, 'Zimbabwe', '', '716', 'ZW', 'ZWE', '', '%company\r\n%firstname %lastname\r\n%address1\r\n%address2\r\n%postcode %city\r\n%zone_name\r\n%country_name', '', 0, 'en', 'ZWD', '263', NOW(), NOW());
-- --------------------------------------------------------
INSERT INTO `lc_currencies` (`status`, `code`, `number`, `name`, `value`, `decimals`, `prefix`, `suffix`, `priority`, `date_updated`, `date_created`) VALUES
(1, 'USD', '840', 'US Dollars', 1, 2, '$', '', 0, NOW(), NOW()),
(1, 'EUR', '978', 'Euros', 0.726, 2, '', ' €', 0, NOW(), NOW());
-- --------------------------------------------------------
INSERT INTO `lc_languages` (`status`, `code`, `code2`, `name`, `locale`, `charset`, `raw_date`, `raw_time`, `raw_datetime`, `format_date`, `format_time`, `format_datetime`, `decimal_point`, `thousands_sep`, `priority`, `date_updated`, `date_created`) VALUES
(1, 'en', 'eng', 'English', 'en_US.utf8,en_US.UTF-8,english', 'UTF-8', 'm/d/y', 'h:i:s A', 'm/d/y h:i:s A', '%b %e %Y', '%I:%M %p', '%b %e %Y %I:%M %p', '.', ',', 0, NOW(), NOW());
-- --------------------------------------------------------
INSERT INTO `lc_order_statuses` (`id`, `icon`, `color`, `is_sale`, `priority`, `date_updated`, `date_created`) VALUES
(1, 'fa-money', '#c0c0c0', 0, 1, NOW(), NOW()),
(2, 'fa-clock-o', '#d7d96f', 1, 2, NOW(), NOW()),
(3, 'fa-cog', '#ffa851', 1, 3, NOW(), NOW()),
(4, 'fa-truck', '#99cc66', 1, 4, NOW(), NOW()),
(5, 'fa-times', '#ff6666', 0, 5, NOW(), NOW());
-- --------------------------------------------------------
INSERT INTO `lc_order_statuses_info` (`id`, `order_status_id`, `language_code`, `name`, `description`) VALUES
(1, 1, 'en', 'Awaiting payment', ''),
(2, 2, 'en', 'Pending', ''),
(3, 3, 'en', 'Processing', ''),
(4, 4, 'en', 'Dispatched', ''),
(5, 5, 'en', 'Cancelled', '');
-- --------------------------------------------------------
INSERT INTO `lc_quantity_units` (`id`, `decimals`, `priority`, `date_updated`, `date_created`) VALUES
(1, 0, 0, NOW(), NOW());
-- --------------------------------------------------------
INSERT INTO `lc_quantity_units_info` (`id`, `quantity_unit_id`, `language_code`, `name`, `description`) VALUES
(1, 1, 'en', 'pcs', '');
-- --------------------------------------------------------
INSERT INTO `lc_settings_groups` (`key`, `name`, `description`, `priority`) VALUES
('store_info', 'Store Info', 'Store information', 10),
('defaults', 'Defaults', 'Store default settings', 20),
('general', 'General', 'Store default settings', 30),
('listings', 'Listings', 'Settings for the catalog listing', 40),
('images', 'Images', 'Settings for graphical elements', 50),
('checkout', 'Checkout', 'Checkout settings', 60),
('advanced', 'Advanced', 'Advanced settings', 70),
('security', 'Security', 'Site security and protection against threats', 80);
-- --------------------------------------------------------
INSERT INTO `lc_settings` (`setting_group_key`, `type`, `title`, `description`, `key`, `value`, `function`, `priority`, `date_updated`, `date_created`) VALUES
('store_info', 'global', 'Store Name', 'The name of your store.', 'store_name', '{STORE_NAME}', 'input()', 10, NOW(), NOW()),
('store_info', 'global', 'Store Email', 'The store e-mail address.', 'store_email', '{STORE_EMAIL}', 'input()', 11, NOW(), NOW()),
('store_info', 'local', 'Store Tax ID', 'The store tax ID or VATIN.', 'store_tax_id', 'XX000000000000', 'input()', 12, NOW(), NOW()),
('store_info', 'local', 'Store Postal Address', 'The store postal address.', 'store_postal_address', 'My Store\r\nStreet\r\nPostcode City\r\nCountry', 'bigtext()', 13, NOW(), NOW()),
('store_info', 'local', 'Store Visiting Address', 'The store visiting address if applicable.', 'store_visiting_address', '', 'bigtext()', 14, NOW(), NOW()),
('store_info', 'local', 'Store Phone Number', 'The store phone number.', 'store_phone', '+1-212-555-DUCK', 'input()', 15, NOW(), NOW()),
('store_info', 'global', 'Store Country', 'The country of your store.', 'store_country_code', '{STORE_COUNTRY_CODE}', 'countries()', 16, NOW(), NOW()),
('store_info', 'global', 'Store Time Zone', 'The store time zone.', 'store_timezone', '{STORE_TIME_ZONE}', 'timezones()', 17, NOW(), NOW()),
('store_info', 'local', 'Store Language', 'The spoken language of your organization.', 'store_language_code', 'en', 'languages()', 18, NOW(), NOW()),
('store_info', 'global', 'Store Currency', 'The currency of which all prices conform to.', 'store_currency_code', 'USD', 'currencies()', 19, NOW(), NOW()),
('store_info', 'global', 'Store Zone', 'The zone of your store.', 'store_zone_code', '', 'zones()', 20, NOW(), NOW()),
('store_info', 'global', 'Store Weight Class', 'The prefered weight class.', 'store_weight_class', 'kg', 'weight_classes()', 21, NOW(), NOW()),
('store_info', 'global', 'Store Length Class', 'The prefered length class.', 'store_length_class', 'cm', 'length_classes()', 22, NOW(), NOW()),
('defaults', 'global', 'Default Language', 'The default language selected, if failed to identify.', 'default_language_code', 'en', 'languages()', 10, NOW(), NOW()),
('defaults', 'global', 'Default Currency', 'The default currency selected, if failed to identify.', 'default_currency_code', 'USD', 'currencies()', 11, NOW(), NOW()),
('defaults', 'global', 'Default Country', 'The default country selected if not set otherwise.', 'default_country_code', '{STORE_COUNTRY_CODE}', 'countries()', 12, NOW(), NOW()),
('defaults', 'global', 'Default Zone', 'The default zone selected if not set otherwise.', 'default_zone_code', '', 'zones()', 13, NOW(), NOW()),
('defaults', 'local', 'Default Tax Class', 'Default tax class that will be preset when creating new products.', 'default_tax_class_id', '1', 'tax_classes()', 14, NOW(), NOW()),
('defaults', 'global', 'Default Display Prices Including Tax', 'Displays prices including tax by default.', 'default_display_prices_including_tax', '1', 'toggle()', 15, NOW(), NOW()),
('defaults', 'global', 'Default Quantity Unit', 'Default quantity unit that will be preset when creating new products.', 'default_quantity_unit_id', '1', 'quantity_units()', 16, NOW(), NOW()),
('defaults', 'global', 'Default Sold Out Status', 'Default sold out status that will be preset when creating new products.', 'default_sold_out_status_id', '1', 'sold_out_statuses()', 17, NOW(), NOW()),
('defaults', 'global', 'Default Delivery Status', 'Default delivery status that will be preset when creating new products.', 'default_delivery_status_id', '1', 'delivery_statuses()', 18, NOW(), NOW()),
('general', 'global', 'Set Currency by Language', 'Chain select currency when changing language.', 'set_currency_by_language', '1', 'toggle()', 10, NOW(), NOW()),
('general', 'global', 'Catalog Only Mode', 'Disables the cart and checkout features leaving only a browsable catalog.', 'catalog_only_mode', '0', 'toggle("t/f")', 11, NOW(), NOW()),
('listings', 'local', 'Items Per Page', 'The number of items to be displayed per page.', 'items_per_page', '20', 'int()', 10, NOW(), NOW()),
('listings', 'local', 'Data Table Rows', 'The number of data table rows per page.', 'data_table_rows_per_page', '25', 'input()', 11, NOW(), NOW()),
('listings', 'local', 'Display Stock Count', 'Show the available amounts of products in stock.', 'display_stock_count', '1', 'toggle()', 12, NOW(), NOW()),
('listings', 'local', 'Cheapest Shipping', 'Display the cheapest shipping cost on product page.', 'display_cheapest_shipping', '1', 'toggle()', 13, NOW(), NOW()),
('listings', 'local', 'Max Age for New Products', 'Display the new sticker for products younger than the give age. E.g. 1 month or 14 days', 'new_products_max_age', '1 month', 'input()', 14, NOW(), NOW()),
('listings', 'local', 'Similar Products Box: Number of Items', 'The maximum amount of items to be display in the box.', 'box_similar_products_num_items', '10', 'int()', 15, NOW(), NOW()),
('listings', 'local', 'Recently Viewed Products Box: Number of Items', 'The maximum amount of items to be display in the box.', 'box_recently_viewed_products_num_items', '4', 'int()', 16, NOW(), NOW()),
('listings', 'local', 'Latest Products Box: Number of Items', 'The maximum amount of items to be display in the box.', 'box_latest_products_num_items', '10', 'int()', 17, NOW(), NOW()),
('listings', 'local', 'Most Popular Products Box: Number of Items', 'The maximum amount of items to be display in the box.', 'box_most_popular_products_num_items', '10', 'int()', 18, NOW(), NOW()),
('listings', 'local', 'Campaign Products Box: Number of Items', 'The maximum amount of items to be display in the box.', 'box_campaign_products_num_items', '5', 'int()', 19, NOW(), NOW()),
('images', 'local', 'Category Images: Aspect Ratio', 'The aspect ratio of the category thumbnails', 'category_image_ratio', '16:9', 'select("1:1","2:3","3:2","3:4","4:3","16:9")', '10', NOW(), NOW()),
('images', 'local', 'Product Images: Aspect Ratio', 'The aspect ratio of the product thumbnails', 'product_image_ratio', '1:1', 'select("1:1","2:3","3:2","3:4","4:3","16:9")', '30', NOW(), NOW()),
('images', 'local', 'Product Images: Clipping Method', 'The clipping method used for scaled product thumbnails.', 'product_image_clipping', 'CROP', 'select("CROP","FIT","FIT_USE_WHITESPACING")', '31', NOW(), NOW()),
('images', 'local', 'Product Images: Watermark', 'Watermark product images with the store logo.', 'product_image_watermark', '0', 'toggle("y/n")', '33', NOW(), NOW()),
('images', 'local', 'Downsample', 'Downsample large uploaded images to best fit within the given dimensions of "width,height" or leave empty. Default: 2048,2048', 'image_downsample_size', '2048,2048', 'smallinput()', '34', NOW(), NOW()),
('images', 'local', 'Image Quality', 'The JPEG quality for uploaded images (0-100). Default: 90', 'image_quality', '90', 'int()', '40', NOW(), NOW()),
('images', 'local', 'Thumbnail Quality', 'The JPEG quality for thumbnail images (0-100). Default: 65', 'image_thumbnail_quality', '65', 'int()', '41', NOW(), NOW()),
('images', 'local', 'Whitespace Color', 'Set the color of any generated whitespace to the given RGB value. Default: 255,255,255', 'image_whitespace_color', '255,255,255', 'smallinput()', '42', NOW(), NOW()),
('checkout', 'local', 'Register Guests', 'Automatically create accounts for all guests.', 'register_guests', '0', 'toggle()', 10, NOW(), NOW()),
('checkout', 'local', 'Password Field', 'If Register Guests is enabled, show the password field letting customers set their own password. Otherwise randomly generated.', 'fields_customer_password', '0', 'toggle()', 11, NOW(), NOW()),
('checkout', 'local', 'Order Copy Receipients', 'Send order copies to the following e-mail addresses. Separate by semi-colons.', 'email_order_copy', '{STORE_EMAIL}', 'mediumtext()', 12, NOW(), NOW()),
('checkout', 'global', 'Round Amounts', 'Round currency amounts to prevent hidden decimals.', 'round_amounts', '0', 'toggle()', 13, NOW(), NOW()),
('advanced', 'global', 'System Cache Enabled', 'Enables the system cache module which caches frequently used data.', 'cache_enabled', '0', 'toggle()', 10, NOW(), NOW()),
('advanced', 'global', 'Clear System Cache', 'Remove all cached system information.', 'cache_clear', '0', 'toggle()', 11, NOW(), NOW()),
('advanced', 'global', 'Clear Thumbnails Cache', 'Remove all cached image thumbnails from disk.', 'cache_clear_thumbnails', '0', 'toggle()', 12, NOW(), NOW()),
('advanced', 'global', 'SEO Links Language Prefix', 'Begins the SEO links with the language code i.e. /en/....', 'seo_links_language_prefix', '1', 'toggle()', 13, NOW(), NOW()),
('advanced', 'global', 'Regional Settings Screen', 'Enables the regional settings screen upon first visit.', 'regional_settings_screen_enabled', '0', 'toggle()', 14, NOW(), NOW()),
('advanced', 'global', 'Jobs Last Run', 'Time when background jobs where last executed.', 'jobs_last_run', NOW(), 'input()', 15, NOW(), NOW()),
('advanced', 'global', 'GZIP Enabled', 'Compresses browser data. Increases the load on the server but decreases the bandwidth.', 'gzip_enabled', '1', 'toggle()', 16, NOW(), NOW()),
('advanced', 'local', 'Jobs Interval', 'The amount of minutes between each execution of jobs.', 'jobs_interval', '60', 'int()', 17, NOW(), NOW()),
('advanced', 'local', 'Database Admin Link', 'The URL to your database manager i.e. phpMyAdmin.', 'database_admin_link', '?app=settings&doc=advanced&action=edit&key=database_admin_link', 'input()', 18, NOW(), NOW()),
('advanced', 'local', 'Webmail Link', 'The URL to your webmail client.', 'webmail_link', '?app=settings&doc=advanced&action=edit&key=webmail_link', 'input()', 19, NOW(), NOW()),
('advanced', 'global', 'SEO Links Enabled', 'Enabling this requires .htaccess and mod_rewrite rules.', 'seo_links_enabled', '1', 'toggle()', 20, NOW(), NOW()),
('security', 'global', 'Blacklist', 'Deny blacklisted clients access to the site.', 'security_blacklist', '0', 'toggle("e/d")', 10, NOW(), NOW()),
('security', 'global', 'Session Hijacking Protection', 'Destroy sessions that were signed for a different IP address and user agent.', 'security_session_hijacking', '0', 'toggle("e/d")', 11, NOW(), NOW()),
('security', 'global', 'HTTP POST Protection', 'Deny incoming HTTP POST data from external sites by checking for valid form tickets.', 'security_http_post', '0', 'toggle("e/d")', 12, NOW(), NOW()),
('security', 'global', 'Bad Bot Trap', 'Catch bad behaving bots from crawling your website by setting up a trap.', 'security_bot_trap', '0', 'toggle("e/d")', 13, NOW(), NOW()),
('security', 'global', 'Cross-site Scripting (XSS) Detection', 'Detect common XSS attacks and deny access to the site.', 'security_xss', '1', 'toggle("e/d")', 14, NOW(), NOW()),
('security', 'local', 'CAPTCHA', 'Prevent robots from posting form data by enabling CAPTCHA security.', 'captcha_enabled', '1', 'toggle()', 15, NOW(), NOW()),
('', 'global', 'Catalog Template', '', 'store_template_catalog', 'default.catalog', 'templates("catalog")', 0, NOW(), NOW()),
('', 'global', 'Admin Template', '', 'store_template_admin', 'default.admin', 'templates("admin")', 0, NOW(), NOW()),
('', 'global', 'Catalog Template Settings', '', 'store_template_catalog_settings', '', '', 0, NOW(), NOW()),
('', 'global', 'Jobs Last Push', 'Time when background jobs where last pushed for execution.', 'jobs_last_push', NOW(), 'input()', 0, NOW(), NOW()),
('', 'local', 'Installed Job Modules', '', 'jobs_modules', '', '', 0, NOW(), NOW()),
('', 'local', 'Installed Shipping Modules', '', 'shipping_modules', '', '', 0, NOW(), NOW()),
('', 'local', 'Installed Payment Modules', '', 'payment_modules', '', '', 0, NOW(), NOW()),
('', 'local', 'Installed Order Action Modules', '', 'order_action_modules', '', '', 0, NOW(), NOW()),
('', 'local', 'Installed Order Total Modules', '', 'order_total_modules', 'ot_subtotal;ot_payment_fee;ot_shipping_fee', '', 0, NOW(), NOW()),
('', 'local', 'Installed Customer Modules', '', 'customer_modules', '', '', 0, NOW(), NOW()),
('', 'local', 'Installed Order Success Modules', '', 'order_success_modules', '', '', 0, NOW(), NOW()),
('', 'local', '', '', 'ot_payment_fee', 'a:1:{s:10:"sort_order";s:2:"10";}', '', 0, NOW(), NOW()),
('', 'local', '', '', 'ot_shipping_fee', 'a:1:{s:10:"sort_order";s:2:"10";}', '', 0, NOW(), NOW()),
('', 'local', '', '', 'ot_subtotal', 'a:1:{s:10:"sort_order";s:1:"1";}', '', 0, NOW(), NOW()),
('', 'local', 'Date Cache Cleared', 'Do not use system cache older than breakpoint.', 'cache_system_breakpoint', NOW(), 'input()', 0, NOW(), NOW());