<?php
  
  $deleted_files = array(
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'ajax/cart.json.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'ajax/checkout_cart.html.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'ajax/checkout_customer.html.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'ajax/checkout_payment.html.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'ajax/checkout_shipping.html.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'ajax/checkout_summary.html.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'ajax/get_address.json.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'ajax/option_values.json.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'ajax/zones.json.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'feeds/sitemap.xml.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'includes/boxes/account.inc.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'includes/boxes/also_purchased_products.inc.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'includes/boxes/campaigns.inc.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'includes/boxes/cart.inc.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'includes/boxes/categories.inc.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'includes/boxes/category_tree.inc.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'includes/boxes/filter.inc.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'includes/boxes/footer_categories.inc.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'includes/boxes/footer_information.inc.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'includes/boxes/footer_manufacturers.inc.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'includes/boxes/latest_products.inc.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'includes/boxes/login.inc.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'includes/boxes/logotypes.inc.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'includes/boxes/manufacturers.inc.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'includes/boxes/most_popular.inc.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'includes/boxes/region.inc.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'includes/boxes/search.inc.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'includes/boxes/similar_products.inc.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'includes/boxes/site_links.inc.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'includes/boxes/site_menu.inc.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'includes/boxes/slider.inc.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'includes/library/lib_seo_links.inc.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'includes/modules/seo_links/url_category.inc.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'includes/modules/seo_links/url_customer_service.inc.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'includes/modules/seo_links/url_information.inc.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'includes/modules/seo_links/url_manufacturer.inc.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'includes/modules/seo_links/url_product.inc.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'includes/modules/seo_links/url_search.inc.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'categories.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'category.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'checkout.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'create_account.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'customer_service.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'edit_account.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'error_document.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'information.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'login.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'logout.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'manufacturer.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'manufacturers.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'order_history.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'order_process.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'order_success.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'printable_order_copy.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'product.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'push_jobs.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'search.php',
    FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'select_region.php',
  );
  
  foreach ($deleted_files as $pattern) {
    if (!file_delete($pattern)) {
      die('<span class="error">[Error]</span></p>');
    }
  }

?>