<?php

	/*
		This file is a reference for the collection definitions used in the application.
		It defines the collections, their names, entities, and how they are identified.

	*/

	// Define collections
	return [
		[
			'id' => 'administrators',
			'name' => t('title_administrators', 'Administrators'),
			'entity' => 'administrator',
			'identified_by' => ['id', 'username', 'email'],
			'translatable' => false,
		],
		[
			'id' => 'attribute_groups',
			'name' => t('title_attribute_groups', 'Attribute Groups'),
			'entity' => 'attribute_group',
			'identified_by' => ['id'],
			'translatable' => ['name'],
		],
		[
			'id' => 'attribute_values',
			'name' => t('title_attribute_values', 'Attribute Values'),
			'entity' => 'attribute_value',
			'identified_by' => ['id'],
			'translatable' => ['name'],
		],
		[
			'id' => 'banners',
			'name' => t('title_banners', 'Banners'),
			'entity' => 'banner',
			'identified_by' => ['id'],
			'translatable' => false,
		],
		[
			'id' => 'brands',
			'name' => t('title_brands', 'Brands'),
			'entity' => 'brand',
			'identified_by' => ['id'],
			'translatable' => ['description', 'short_description', 'head_title', 'meta_description'],
		],
		[
			'id' => 'categories',
			'name' => t('title_categories', 'Categories'),
			'entity' => 'category',
			'identified_by' => ['id'],
			'translatable' => ['name', 'short_description', 'description', 'head_title', 'h1_title', 'meta_description'],
		],
		[
			'id' => 'countries',
			'name' => t('title_countries', 'Countries'),
			'entity' => 'country',
			'identified_by' => ['id'],
			'translatable' => false,
		],
		[
			'id' => 'currencies',
			'name' => t('title_currencies', 'Currencies'),
			'entity' => 'currency',
			'identified_by' => ['id'],
			'translatable' => false,
		],
		[
			'id' => 'customer_groups',
			'name' => t('title_customer_groups', 'Customer Groups'),
			'entity' => 'customer_group',
			'identified_by' => ['id'],
			'translatable' => false,
		],
		[
			'id' => 'customers',
			'name' => t('title_customers', 'Customers'),
			'entity' => 'customer',
			'identified_by' => ['id'],
			'translatable' => false,
		],
		[
			'id' => 'delivery_statuses',
			'name' => t('title_delivery_statuses', 'Delivery Statuses'),
			'entity' => 'delivery_status',
			'identified_by' => ['id'],
			'translatable' => ['name', 'description'],
		],
		[
			'id' => 'emails',
			'name' => t('title_emails', 'Emails'),
			'entity' => 'email',
			'identified_by' => ['id'],
			'translatable' => false,
		],
		[
			'id' => 'geo_zones',
			'name' => t('title_geo_zones', 'Geo Zones'),
			'entity' => 'geo_zone',
			'identified_by' => ['id'],
			'translatable' => false,
		],
		[
			'id' => 'languages',
			'name' => t('title_languages', 'Languages'),
			'entity' => 'language',
			'identified_by' => ['id'],
			'translatable' => false,
		],
		[
			'id' => 'modules',
			'name' => t('title_modules', 'Modules'),
			'entity' => 'translation',
			'identified_by' => ['id'],
			'translatable' => false,
		],
		[
			'id' => 'newsletter_recipients',
			'name' => t('title_newsletter_recipients', 'Newsletter Recipients'),
			'entity' => 'newsletter_recipient',
			'identified_by' => ['id', 'email'],
			'translatable' => false,
		],
		[
			'id' => 'order_statuses',
			'name' => t('title_order_statuses', 'Order Statuses'),
			'entity' => 'order_status',
			'identified_by' => ['id'],
			'translatable' => ['name', 'description', 'email_subject', 'email_message'],
		],
		[
			'id' => 'orders',
			'name' => t('title_orders', 'Orders'),
			'entity' => 'order',
			'identified_by' => ['id'],
			'translatable' => false,
		],
		[
			'id' => 'pages',
			'name' => t('title_pages', 'Pages'),
			'entity' => 'page',
			'identified_by' => ['id'],
			'translatable' => ['title', 'head_title', 'meta_description', 'content'],
		],
		[
			'id' => 'products',
			'name' => t('title_products', 'Products'),
			'entity' => 'product',
			'identified_by' => ['id'],
			'translatable' => ['name', 'description', 'short_description', 'technical_data', 'head_title', 'meta_description'],
		],
		[
			'id' => 'quantity_units',
			'name' => t('title_quantity_units', 'Quantity Units'),
			'entity' => 'quantity_unit',
			'identified_by' => ['id'],
			'translatable' => ['name', 'description'],
		],
		[
			'id' => 'redirects',
			'name' => t('title_redirects', 'Redirects'),
			'entity' => 'redirect',
			'identified_by' => ['id'],
			'translatable' => false,
		],
		[
			'id' => 'settings',
			'name' => t('title_settings', 'Settings'),
			'entity' => 'setting',
			'identified_by' => ['key'],
			'translatable' => ['title', 'description'],
		],
		[
			'id' => 'settings_groups',
			'name' => t('title_settings_groups', 'Settings Groups'),
			'entity' => 'setting_group',
			'identified_by' => ['key'],
			'translatable' => ['name'],
		],
		[
			'id' => 'site_tags',
			'name' => t('title_site_tags', 'Site Tags'),
			'entity' => 'site_tag',
			'identified_by' => ['id'],
			'translatable' => false,
		],
		[
			'id' => 'sold_out_statuses',
			'name' => t('title_sold_out_statuses', 'Sold Out Statuses'),
			'entity' => 'sold_out_status',
			'identified_by' => ['id'],
			'translatable' => ['name', 'description'],
		],
		[
			'id' => 'stock_items',
			'name' => t('title_stock_items', 'Stock Items'),
			'entity' => 'stock_item',
			'identified_by' => ['id', 'sku', 'gtin', 'mpn'],
			'translatable' => ['name'],
		],
		[
			'id' => 'stock_transactions',
			'name' => t('title_stock_transactions', 'Stock Transactions'),
			'entity' => 'stock_transaction',
			'identified_by' => ['id'],
			'translatable' => false,
		],
		[
			'id' => 'suppliers',
			'name' => t('title_suppliers', 'Suppliers'),
			'entity' => 'supplier',
			'identified_by' => ['id'],
			'translatable' => false,
		],
		[
			'id' => 'tax_classes',
			'name' => t('title_tax_classes', 'Tax Classes'),
			'entity' => 'tax_class',
			'identified_by' => ['id'],
			'translatable' => false,
		],
		[
			'id' => 'tax_rates',
			'name' => t('title_tax_rates', 'Tax Rates'),
			'entity' => 'tax_rate',
			'identified_by' => ['id'],
			'translatable' => false,
		],
		[
			'id' => 'third_parties',
			'name' => t('title_third_parties', 'Third Parties'),
			'entity' => 'third_party',
			'identified_by' => ['id'],
			'translatable' => ['description', 'collected_data', 'purposes'],
		],
		[
			'id' => 'translations',
			'name' => t('title_translations', 'Translations'),
			'entity' => 'translation',
			'identified_by' => ['code'],
			'translatable' => ['text'],
		],
		[
			'id' => 'vmods',
			'name' => t('title_vmods', 'vMods'),
			'entity' => 'vmod',
			'identified_by' => ['id'],
			'translatable' => false,
		],
	];
